import React from 'react';

export default function Landing() {
    return (
        <div>
            <h1>Michael Callahan</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa id neque aliquam vestibulum morbi blandit cursus risus. Porta nibh venenatis cras sed felis eget. Dolor morbi non arcu risus quis. Ultricies integer quis auctor elit. Ipsum suspendisse ultrices gravida dictum fusce ut. In dictum non consectetur a erat nam at lectus. Aliquam purus sit amet luctus venenatis. Massa tincidunt nunc pulvinar sapien et. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Sed arcu non odio euismod lacinia. Nam libero justo laoreet sit amet cursus sit amet. Cursus vitae congue mauris rhoncus. Ipsum dolor sit amet consectetur. Vitae congue eu consequat ac felis donec. Nullam vehicula ipsum a arcu. Nulla facilisi morbi tempus iaculis urna id. Magnis dis parturient montes nascetur ridiculus.Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Tortor posuere ac ut consequat semper viverra nam libero. Mus mauris vitae ultricies leo integer malesuada nunc vel. Turpis massa sed elementum tempus. Vulputate dignissim suspendisse in est ante in. Ullamcorper eget nulla facilisi etiam dignissim. Lorem ipsum dolor sit amet. Quisque id diam vel quam. Sagittis vitae et leo duis ut. Elit duis tristique sollicitudin nibh. Porttitor massa id neque aliquam vestibulum. Et netus et malesuada fames. Tristique nulla aliquet enim tortor at auctor.Fringilla est ullamcorper eget nulla facilisi etiam dignissim. Id diam maecenas ultricies mi eget mauris pharetra et ultrices. Molestie nunc non blandit massa enim nec. Non quam lacus suspendisse faucibus interdum posuere. Et molestie ac feugiat sed lectus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur. Ut eu sem integer vitae justo. Velit scelerisque in dictum non consectetur a erat. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Eu non diam phasellus vestibulum lorem sed risus ultricies. Porta nibh venenatis cras sed felis eget. Quam pellentesque nec nam aliquam. Euismod elementum nisi quis eleifend. Eget felis eget nunc lobortis mattis aliquam faucibus. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Nullam vehicula ipsum a arcu. Nam at lectus urna duis convallis convallis tellus. Viverra mauris in aliquam sem. Tristique nulla aliquet enim tortor at auctor urna.</p>
        </div>
    );
}